Add 6 social links
fossasia/2015.fossasia.org pull request #88
Opened 2018-01-06 17:33 UTC by kubami9

**Add 6 github links for:**
 - Hong Phuc Dang
 - Mario Behling
 - Harish Pillay
 - Roland Turner
 - Darwin Gosal
 - Archy Wilhes

2018-01-06 18:14 UTC, isuruAb approved these changes

2018-01-06 18:15 UTC, isuruAb commented
@kubami9  please provide a demo link

2018-01-06 20:45 UTC, kubami9 commented
@isuruAb I made this link: https://kubami9.github.io/2015.fossasia.org-km-contribute/, however it doesn't show any changes and I don't know why since index.html is changed 🤔

2018-01-07 13:49 UTC, akshatnitd reviewed
You need to change the github icon class name, since this class doesn't show the icons!

2018-01-07 13:52 UTC, akshatnitd requested changes
Try to add a github icon, the one you added is for external links

2018-01-07 13:54 UTC, abishekvashok requested changes

2018-01-07 13:54 UTC, abishekvashok commented on index.html
> +													<i class="icon icon_link_alt"></i>
You need a social_github class here

2018-01-07 16:23 UTC, kubami9 commented
@akshatnitd done and merged 😄

2018-01-07 17:29 UTC, akshatnitd approved these changes

2018-01-07 17:29 UTC, merged

2018-01-07 17:30 UTC, akshatnitd commented
@kubami9 Great work :)

2018-01-07 17:54 UTC, kubami9 commented
Thank you! :D